[mgr]
border_symbol = "│"
border_style = { fg = "#0d0d0d" } # black

[status]
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }

[mode]
# Default bg.
normal_main = { fg = "#202020", bg = "#81a2be" } # blue
select_main = { fg = "#202020", bg = "#cc6666" } # red
unset_main = { fg = "#202020", bg = "#de935f" }  # yellow

[indicator]
padding = { open = "█", close = "█" }

# tomorrow_night:
#
# base00 = "#1d1f21",
# base01 = "#282a2e",
# base02 = "#373b41",
# base03 = "#969896",
# base04 = "#b4b7b4",
# base05 = "#c5c8c6",
# base06 = "#e0e0e0",
# base07 = "#ffffff",
# base08 = "#cc6666",
# base09 = "#de935f",
# base0A = "#f0c674",
# base0B = "#b5bd68",
# base0C = "#8abeb7",
# base0D = "#81a2be",
# base0E = "#b294bb",
# base0F = "#a3685a",
