name: Checks in PR

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  cocogitto-pr:
    runs-on: ubuntu-latest
    name: check conventional commits
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
      - name: Check the Pull Request title
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        shell: nix shell nixpkgs#cocogitto --quiet --command bash {0}
        run: |
          git config user.name "github-actions-workflow"
          git config user.email "temp@users.noreply.github.com"
          cog verify "$PR_TITLE"
